### PR TITLE
Add index.js

### PR DESCRIPTION
**Pull request by Diyahon**

### CODE REVIEW

**Comment by sroze** [comment]
Could you detail why you proposed this change? Also, don't you think that changing the main file will break some of the installs? ;)

**Comment by sroze** [comment]
ping @Diyahon

**Comment by Diyahon** [comment]
This is comfortably for webpack. And is not broke if add this code to main file:
`if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports){
module.exports = 'infinite-scroll';
}`
Then don't need change main file in package.json.

**Comment by sroze** [comment]
Could you then update your PR so we don't have to update the `package.json`
file?

**Comment by Diyahon** [comment]
Sorry, I was busy with work. I will do it on this holidays.

**Comment by graingert** [comment]
closing in favour of https://github.com/sroze/ngInfiniteScroll/pull/271

**Pull request closed without merging**
