### PR TITLE
Add custom event listener to trigger handler manually.

### LINKED ISSUE #94: Triggering scroll event when the element becomes shorter
I have a list with items that can be filtered in or out. I'm using ngInfiniteScroll in this list.

The issue I'm having is that say if I have 1 apple and 9 oranges in my list, and then I click the button to filter out oranges, my list is suddenly only one item long and really needs repopulating. But since ngInfiniteScroll only responds to scroll events, the user has to attempt a scroll before repopulation can happen (and they might not think to do this).

My current solution is to have a function in my controller:

```javascript
var triggerScroll = function(){
    setTimeout(function(){
        $(window).scroll()
    },4)
}
```

(The timeout is there because if I remove the items, then call `$(window).scroll()`, the event is fired before the digest cycle. This means the items haven't been removed from the DOM and so the list is the same height.)

This obviously isn't ideal. 

I'm wondering if there's a case here for ngInfiniteScroll to watch for DOM changes — but unsure due to browser support and increased complexity. The alternative seems to be to be able to do some nicer method of the above — ask ngInfiniteScroll to check after the next digest cycle somehow.

Any ideas? Happy to write a PR for this.

### PR DESCRIPTION
**Pull request by neoeno**
Resolves #94. Use-case detailed there. Tests included.

Example:

```html
<div infinite-scroll='loadMore()' infinite-scroll-listen-for-event="anEventName">
  <p ng-repeat="item in items">item</p>
</div>
```

And in your controller, when you need to manually trigger the scroll check:

```javascript
$scope.$emit('anEventName')
```

### CODE REVIEW

**Comment by neoeno** [comment]
We got there eventually. Build passes!

**Comment by sroze** [comment]
Even if we're adding too much attributes that seems great ! Thanks @neoeno

**Comment by neoeno** [comment]
:+1: I did think that about the attributes actually! Couldn't think of an alternative though.

Would you like a PR for the docs?

**Comment by sroze** [comment]
If you can do it it'd be great !
Btw, I'll work on a 2.0 version where every issues is resolved and without so much attributes :)

**Pull request merged**
