### PR TITLE
Adds support on initial load and manual trigger to load until the pag…

### LINKED ISSUE #118: Modify data collection
Hi. Great module! 

I only miss here one thing. 
I load data on controller initialize like [here in demo](http://sroze.github.io/ngInfiniteScroll/demo_async.html). It is working like a charm.
But when i try to reload data with some different url prameters (filtering in my case) it is not reflected until i scroll.

### LINKED ISSUE #125: Trigger infinite-scroll until scrollbar appears or disabled = false
Trigger `infinite-scroll="nextSlot()"` until the scrollbar appears or disabled = false.

With large windows, not all content is shown, because a scrollbar does not appear. Without scrollbar, user cannot scroll, therefore, only the first contents will be shown

### PR DESCRIPTION
**Pull request by solomon87**
Adds support on initial load and manual trigger to load until the page is full - fixes #125

### CODE REVIEW

**Comment by sroze** [comment]
Can you let me know how you would "manually trigger" the load with this PR?

**Comment by solomon87** [comment]
Hey, this uses the existing 'infinite-scroll-listen-for-event' mechanism. It simply calls my new load() function instead of handler() directly. Basically I'm wrapping handler() in a $interval for the initial load and when the event is triggered. The $interval runs until handler() returns false indicating that that page is full.

**Comment by solomon87** [comment]
Looks like the build failed due to a timeout issue with saucelabs selenium server. Is this something you are interested in merging into your branch? I'm also about to check-in a bug fix against this. $interval only runs once in firefox when the delay argument is not provided.

**Comment by solomon87** [comment]
I'm going to close this pull request for now. I need to make sure it will meet all the test requirements.

**Pull request closed without merging**
