### PR TITLE
Infinite scroll on any element.

### PR DESCRIPTION
**Pull request by tcard**
Sets two new attributes: infinite-scroll-container, which replaces $window with an arbitrary scrollable element, and the helper infinite-scroll-parent, which replaces $window with the element's parent.

### CODE REVIEW

**Comment by jdiaz07** [comment]
Hi guys,

I've been working with this directive and it's just fantastic! However, i have some issues with scrolling.

What happens is that scroll event actions is executing even when i'm not really scrolling the infinite scroll container, has any of you experienced this same problem? 

Any help will be appreciated! Thanks!

**Comment by takeit** [comment]
@MarcLoupias thanks! that worked very well, I will only add Im using version 1.2.0 of ngInfinite.

**Comment by makrem025** [comment]
Thanks for the good work!

@PaulMougel I have used this for a site now, and it works fine on iPhone 4/5/6 and iPad mini as far as I have seen.

**Comment by JQGuo** [comment]
Was having an issue getting infinite scroll to work and found the solution. It wasn't a problem with the ngInfiniteScroll code though, but I just thought I'd post it here for anyone who is using the same frameworks.

I've been trying to get infinite scroll working on a sidebar container in a project that uses Angular Material Design. I managed to see scroll events firing on the right element using infinite-scroll-parent='true', but it was firing every time I scrolled. So I was debugging the infinite scroll code when I saw that elementBottom and remaining were negative. It appears that having layout="column" (I think its an HTML attribute only used by the material design code) on your element causes something weird to happen. If you scroll, the div appears in the right location visually, but it actually scrolls up in the DOM viewer, so it makes sense that the element offsets are negative. So the fix for me was just removing that attribute. I'm not really a front-end developer so idk if this behaviour is a bug with Material Design or not.

Anyways, took me quite awhile to figure out, hope this helps others out that are using both Material Design and ngInfiniteScroll.

**Comment by mgonzalez10** [comment]
My problem was similar to @JQGuo because every time I scrolling, the page events was fired. It was because the div element with ng-repeat had assigned a style float: left.

**Comment by dopgm** [comment]
@mgonzalez10 
You are right, when I removed float I started getting just the first page (instead of all at once), but only the first page: when I reach the bottom - no progress, is does not fire up a call to fetch the next data set.
Any thoughts?

Thanks!
D.

**Comment by fcristel** [comment]
I'm getting the same problem as @dopgm . The nextPage isn't fetching the next results. I'm only getting the first page when in a modal

**Comment by ramirekik** [comment]
I resolved the issue with adding infinite-scroll-parent on the element, it works fine on ng-infinite-scroll: 1.3.0

**Comment by ytianzaishui** [comment]
I use  infinite scroll on ng-dialog in a div, it works ,but when i scroll function `infinite-scroll="mypageFun()"`   works every time .
```
<div class="tags-scroll"
                     id="tags-scroll">
                    <div infinite-scroll-distance="-1"
                         infinite-scroll-parent="true"
                         infinite-scroll-immediate-check="false"
                         infinite-scroll="mypageFun()">
                        <table class="table table-bordered"
                               style="margin-bottom: 0;">
                            <tbody>
                            <tr ng-repeat="item in LargeCNCulturalData" ng-if="LargeCNCulturalData.length">
                                <td>{{item.tagName}}</td>
                                <td>
                                    <input id="{{item.tagId}}"
                                           type="checkbox"
                                           ng-checked="largeIsCheckTag(isRepeatList,item.tagId)"
                                           ng-click="largeGetCheckTags($event,item.tagId,item.tagName,item.tagPriority)">
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
```

**Comment by nkmishra1997** [comment]
I have a scroll-able div and my main page is also scrollable. In my case, the desired behavior is that the `loadMore()`  function is fired only when I scroll inside my scrollable div and not when I am scrolling the main page. Right now, the `loadMore()` is fired even if I scroll the main window.  I have followed the example in [#7 (comment)](https://github.com/sroze/ngInfiniteScroll/pull/7#issuecomment-42402768). Has anyone achieved this kind of behavior?  If yes, kindly share the work-around. Thanks!

**Pull request merged**
