### PR TITLE
add documentation for container, use-document-bottom, scroll-parent a…

### LINKED ISSUE #57: Add documentation about the `infinite-scroll-container` directive
Documentation of #7.

### LINKED ISSUE #204: Missing documentation
I would submit a pull but documentation is not part of this repository.

Missing documentation appears to be:

* **infinite-scroll-container** - An expression that results in an HTMLElement object, an array whose first element is evaluated using angular.element(),or  a string which is used as the parameter to document.querySelector().  The selector is similar to jQuery selectors but should evaluate to a single element.  Remember to use single quotes around string constants.  See http://plnkr.co/edit/m2HUv9xKKpebSIjMfsxT?p=preview for an example.
* **infinite-scroll-use-document-bottom** - An expression that evaluates to boolean.  If true, the distance to the bottom of the document is used in conjunction with infinite-scroll-distance rather than the scroll distance to the bottom of the element on which the ngInfiniteScroll directive is placed.
* **infinite-scroll-parent** - If this attribute exists, the scroll container that is tracked is the parent element of the element on which the ngInfiniteScroll directive is placed.  See http://plnkr.co/edit/dkDsBA57jT0VQWBPyIEy?p=preview

### PR DESCRIPTION
**Pull request by rcollette**
…ttributes.

fixes #204, fixes #57

### CODE REVIEW

**Comment by graingert** [comment]
Can you mark this commit as fixing the issue?

**Comment by graingert** [comment]
You need to add #Fixes ... to the commit

**Comment by lilnate22** [comment]
+1

**Comment by rcollette** [comment]
I tried doing `git --amend` but I'm not sure it worked exactly right.  I'm seeing three commits now.

**Comment by graingert** [comment]
You've done a merge for some reason

Do `git rebase -i ad12286eabac0ad251d29e49a9dca4b7a9c8a385~1` and clean up your commits

**Comment by rcollette** [comment]
I think it looks good now.

**Comment by graingert** [comment]
You should still include the commit message...

**Comment by rcollette** [comment]
Sorry.  I'm done with it.  Someone else can fix it up if they want it in.

**Pull request closed without merging**
