### PR TITLE
Export the module to make it RequireJS compatible.

### PR DESCRIPTION
**Pull request by dsnoeck**
Refer to the comment of @Diyahon here: https://github.com/sroze/ngInfiniteScroll/pull/252#issuecomment-186113787

### CODE REVIEW

**Comment by dsnoeck** [comment]
Hey @sroze, is it possible to merge this pull request ? My current project is waiting for it.
Thanks a lot.

**Comment by graingert** [comment]
@dsnoeck please rebase/squash your changes

**Comment by graingert** [comment]
@dsnoeck also can you update the documentation, please

**Comment by dsnoeck** [comment]
@graingert, I so you already have added the code for exporting the module. What more you want to add in the documentation ?

**Comment by graingert** [comment]
@dsnoeck sorry, I've already updated the documentation!

**Pull request closed without merging**
