### PR TITLE
Add support for mobile.

### PR DESCRIPTION
**Pull request by evermax**
Hi!

I wanted to use your library for mobile, so I made those small changes.
What do you think about adding this to support mobile?

### CODE REVIEW

**Comment by evermax** [comment]
I was a bit too enthusiastic, it doesn't work as expected...

**Comment by surfjedi** [comment]
Im keen to use this on mobile.. how bad is it?

**Comment by evermax** [comment]
For some reason the scroll event isn't triggered on mobile, at least in the setup I used so the library simply wasn't working. I had to trigger it manually and it works perfectly for me now!

**Comment by evermax** [comment]
I just learned that it isn't even because of this directive but because of another framework, mobile angular ui. Sorry for the issue guys...

**Comment by michaelcyyuen** [comment]
Wow! Thank you @evermax  so much for stating this is not working in mobile. I've notice that it won't trigger in mobile bootstrap mode. May I know you trigger statement for reference?

**Comment by michaelcyyuen** [comment]
For Bootstrap mobile. There's a css overflow-x: hidden in body, causing the PageYoffset to be 0. Making my scroller not functioning in mobile view. Once I remove the css, things are fine now.

**Comment by evermax** [comment]
Thanks for the update! I'll know for another time :)

**Pull request closed without merging**
