### PR TITLE
Fixed infinite-scroll-immediate-check behavior

### PR DESCRIPTION
**Pull request by sergiovilar**
When you add `infinite-scroll-immediate-check="true"` to directive, ngInfiniteScroll only call the pagination callback once. 

If even with the first load made by `infinite-scroll-immediate-check` the page content doesn't generate a scroll, ngInfiniteScroll will not trigger the pagination callback again. This causes a problem because ngInfiniteScroll needs the user get to the bottom to call the pagination callback again.

This PR calls the handler() until a scroll appear on the page, solving the problem.

I believe that he guys at #219 had the same problem.

### CODE REVIEW

**Comment by alejandromagnorsky** [comment]
This pull-request seems to fix that error @sergiovilar is mentioning. This feature is essential.

**Comment by jvmccarthy** [comment]
@sroze @sergiovilar Just ran into this today also.  I'm not sure of all the conditions involved, but now I'm seeing a busy loop in the digest cycle because of this code change.  It looks like in some code paths, `checkInteraval` is not canceled. I don't have time to investigate this further at the moment and am pinning to version `1.2.0` for now, but I wanted to give a heads up.

**Comment by eprevot** [comment]
Because of this busy loop, my protractor tests fail with timeout. Going back to 1.2.1

**Comment by jvmccarthy** [comment]
Yes, protractor sync issues also led me to this busy loop.

**Comment by cs-NET** [comment]
Ran into this as well, around 250-300 digests per second. I think because the 1 was removed that we need to increase the delay from 0 to 500ms to prevent the busy loop.

**Comment by cjeffers** [comment]
To add further detail to the protractor sync issue, for me it was: `Timed out waiting for Protractor to synchronize with the page after 11 seconds.` The description in the [protractor docs](https://github.com/angular/protractor/blob/master/docs/timeouts.md#timeouts-from-protractor) mentions this as coming from continuous polling.

Not giving `$interval()` the third `count` parameter [causes it to repeat indefinitely.](https://docs.angularjs.org/api/ng/service/$interval) What was the thinking behind removing that parameter?

Reverting to 1.2.1 allowed my tests to pass.

**Pull request merged**
