### PR TITLE
fix shouldScroll logic Fixes #220"

### LINKED ISSUE #220: Many items are loaded as soon as i move scroll a bit
I have been trying to use this library today, and i have the following problem. I use a div with attribute infinite-scroll to call my load function without any other optional attributes. Inside this div i have an ng-repeat (obviously) where i iterate over my array.

``` javascript
            div(infinite-scroll='vm.loadIdeas()')
              div(ng-class="...", ng-repeat="idea in vm.ideasToShow"
```

My load function adds 10 new items to array each time it is called. And let's say my browser can contain  more or less 10 items without scrolling. And i have 1000 items in total. As soon as i open the page, it looks like (from the position & length of scrollbar) there is already 20-30 items loaded. And as soon as i scroll down a bit, it starts to load all other items, before i even reach at the middle of the page. What can be the problem here?

### PR DESCRIPTION
**Pull request by p4bloch**
Fixes #220 
I've been trying the library and had the same problem. I started to dig in and it turned out that shouldScroll was always true.

This fixes it

### CODE REVIEW

**Comment by nmccready** [comment]
Whats up with this? Why is this not merged?

**Comment by nmccready** [comment]
Confirmed fix

**Comment by nmccready** [comment]
@sroze

**Comment by graingert** [comment]
@p4bloch @nmccready please include a test with this change.

**Comment by graingert** [comment]
@p4bloch your commit message should be "fix shouldScroll logic Fixes #220"

**Comment by nmccready** [comment]
@graingert can you give some guidance on the test? I mean ngInfiniteScroll just doesn't work right without this change. Is there similar existing test that can be modified slightly to confirm this change?

**Comment by graingert** [comment]
@nmccready currently the tests's loadMore function is:
```js
return [].push.apply($rootScope.items, new Array(100));
```
So if shouldScroll is always true, the tests would go into an infinite loop

**Comment by graingert** [comment]
@nmccready can you try out 1.3.0?

**Comment by coyotte508** [comment]
`scrollDistance` can be 0, in which case you have a nice division by 0...

**Pull request closed without merging**
